In [1]:
#importing libraries
import torch
import torch.nn as nn
from torch import sigmoid

In [2]:
#Class for linear function
class Net(nn.Module):
    def __init__(self, D_in,H,D_out):
        super(Net,self).__init__()
        self.linear1 = nn.Linear(D_in,H)
        self.linear2 = nn.Linear(H,D_out)

    def forward(self,x):
        x = sigmoid(self.linear1(x))
        x = sigmoid(self.linear2(x))
        return x
    


In [3]:
model = Net(1,2,1)
x = torch.tensor([0.0])
yhat = model(x)

In [4]:
yhat

tensor([0.5802], grad_fn=<SigmoidBackward0>)

In [5]:
#For Multiple samples
model = Net(1,2,1)
x = torch.tensor([[0.0],[2.0],[1.0]])
yhat = model(x)

In [6]:
yhat

tensor([[0.4420],
        [0.4481],
        [0.4449]], grad_fn=<SigmoidBackward0>)

In [8]:
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[-0.4378],
                      [ 0.3423]])),
             ('linear1.bias', tensor([-0.1114,  0.8891])),
             ('linear2.weight', tensor([[-0.5287, -0.6803]])),
             ('linear2.bias', tensor([0.4989]))])

In [9]:
model.state_dict

<bound method Module.state_dict of Net(
  (linear1): Linear(in_features=1, out_features=2, bias=True)
  (linear2): Linear(in_features=2, out_features=1, bias=True)
)>

In [10]:
pip install nbformat


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import nbformat

with open("neural network with one hidden layer with two neurons.ipynb") as f:
    nb = nbformat.read(f, as_version=4)

with open("fixed_neural network with one hidden layer with two neurons.ipynb", "w") as f:
    nbformat.write(nb, f)
